spring:
  application:
    name: ms-load-database

  cloud:
    aws:
      endpoint: http://localhost:4566
      credentials:
        access-key: fake
        secret-key: fake
      region:
        static: ${AWS_REGION:us-east-1}

server:
  port: ${APPLICATION_PORT:8086}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: [ 'health', 'metrics', 'info' ]
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true

application:
  sqs:
    queues:
      my-queue: my-queue-sqs-local